[package]
name = "aws"
description = "aws"
version = "0.0.1"
authors = ["Graham Lee <ghmlee@ghmlee.com>"]
license = "Apache-2.0"
homepage = "https://github.com/ghmlee/aws"
repository = "https://github.com/ghmlee/aws.git"
readme = "README.md"
keywords = ["aws"]

[dependencies]